Definition of Audit API.
metal-stack-cloud/api pull request #186
Opened 2024-11-29 15:05 UTC by Gerrit91

2025-01-13 13:27 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  string tenant = 6;
Project field should also be present but the backend currently does not offer it.

2025-01-16 06:47 UTC, majst01 requested changes

2025-01-16 06:47 UTC, majst01 commented on proto/api/v1/audit.proto
> +  string method = 8;
should be optional

2025-01-16 06:47 UTC, majst01 commented on proto/api/v1/audit.proto
> +  string uuid = 2 [(buf.validate.field).string.uuid = true];
should be optional

2025-01-16 06:47 UTC, majst01 commented on proto/api/v1/audit.proto
> +  string user = 5;
should be optional

2025-01-16 06:47 UTC, majst01 commented on proto/api/v1/audit.proto
> +  string result_code = 9;
should be optional

2025-01-16 06:47 UTC, majst01 commented on proto/api/v1/audit.proto
> +  string project = 7;
should be optional

2025-01-20 11:00 UTC, majst01 commented on proto/api/v1/audit.proto
> +  string error = 11;
This is not required as all grpc calls will container a error in the response

2025-01-27 11:23 UTC, majst01 commented on proto/api/v1/audit.proto
> +  google.protobuf.Timestamp to = 4;
It might be handy to have also the ability to specify `from` and a duration

2025-03-07 06:08 UTC, majst01 commented on proto/api/v1/audit.proto
> +  optional int32 limit = 12;
Please add validation to all of this fields

2025-03-07 06:08 UTC, majst01 commented on proto/api/v1/audit.proto
> +  string login = 1;
Validation is missing

2025-03-11 16:03 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  //Phase is a string representing the request phase
```suggestion
  // Phase is a string representing the request phase
```

2025-03-25 09:45 UTC, ostempel commented on proto/api/v1/audit.proto
> +  google.protobuf.Timestamp to = 4;
`from` and `to` already support relative timing in cli: `--from 5h --to 1h` for example
And in the console we will utilize date-time-pickers eventually

2025-03-25 10:04 UTC, majst01 approved these changes

2025-04-23 07:43 UTC, Gerrit91 reviewed
Only improvements on comments / docs.

2025-04-23 07:43 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  // ResultCode is a string describing the result of the api call
```suggestion
  // ResultCode is a status code describing the result of the api call. it is set for traces in the response phase and contains official gRPC status codes.
```

2025-04-23 07:43 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  string phase = 10;
An enum for the phases would be nice?

2025-04-23 07:43 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  // User is the user who called the api method
```suggestion
  // User is the login user who called the api method
```

2025-04-23 07:43 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  // Request is the payload of the request
```suggestion
  // Body is the payload of the api call. In the request phase this contains the payload sent by the client, in the request phase it contains the payload returned by the api server.
```

2025-04-23 07:43 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  // Response is the payload of the response
```suggestion
  // Source  IP is contains the source ip address of the api call
```

2025-04-23 07:43 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  // Limit is a number limiting the length of the response (min: 1, max: 1000)
Should we default this? Otherwise the responses may be too large (user that request all audit traces).

2025-04-23 07:43 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  repeated AuditTrace audits = 1;
What is meant by "without secrets"?

```suggestion
  // Traces is a list of audit traces without the secrets
  repeated AuditTrace traces = 1;
```

2025-04-23 07:43 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  AuditTrace audit = 2;
```suggestion
  // Trace is the audit trace
  AuditTrace trace = 2;
```

2025-04-23 08:11 UTC, Gerrit91 reviewed
Only improvements on comments / docs.

2025-04-23 08:11 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  // From describes the start of the time window in which to list audit traces
```suggestion
  // From describes the start of the time window in which to list audit traces (if not specified this defaults to the last eight hours)
```

2025-04-23 08:11 UTC, Gerrit91 commented on proto/api/v1/audit.proto
> +  // To describes the end of the time window in which to list audit traces
```suggestion
  // To describes the end of the time window in which to list audit traces (if not specified this defaults to the time the request was issued)
```

2025-04-23 13:44 UTC, vknabel approved these changes

2025-04-23 13:46 UTC, Gerrit91 commented
We should somehow discuss how we want to deal with default values for the API. It's problematic to write them into the doc strings of the API because this implies an update of the API repository if we want to change the default in the api-server. On the other hand we do not have a documentation portal where we describe these things and clients also should not handle them individually.

2025-04-23 13:46 UTC, merged